import { useEffect, useMemo, useState } from "react";
import { Helmet } from "react-helmet-async";
import { useNavigate } from "react-router-dom";
import { fetchProfile } from "../assets/js/api/profileApi";
import { createTask, deleteTask, fetchTasks, updateTask } from "../assets/js/api/taskApi";
import { createEvent, deleteEvent, fetchEvents } from "../assets/js/api/eventApi";
import productivityHubLightImage from "../assets/images/light_productivity_hub.png";
import productivityHubDarkImage from "../assets/images/dark_productivity_hub.png";

function todayString() {
  return new Date().toISOString().slice(0, 10);
}

function formatDate(value) {
  if (!value) {
    return "No date";
  }

  return new Intl.DateTimeFormat("en-US", {
    month: "short",
    day: "numeric",
    year: "numeric",
  }).format(new Date(`${value}T00:00:00`));
}

function monthLabel(baseDate) {
  return new Intl.DateTimeFormat("en-US", {
    month: "long",
    year: "numeric",
  }).format(baseDate);
}

function buildCalendarDays(currentMonth, events) {
  const year = currentMonth.getFullYear();
  const month = currentMonth.getMonth();
  const firstDay = new Date(year, month, 1);
  const firstGridDay = new Date(firstDay);
  firstGridDay.setDate(firstDay.getDate() - firstDay.getDay());

  return Array.from({ length: 42 }, (_, index) => {
    const date = new Date(firstGridDay);
    date.setDate(firstGridDay.getDate() + index);
    const dateKey = date.toISOString().slice(0, 10);
    return {
      dateKey,
      dayNumber: date.getDate(),
      isCurrentMonth: date.getMonth() === month,
      isToday: dateKey === todayString(),
      events: events.filter((event) => event.eventDate === dateKey),
    };
  });
}

const blankTaskForm = {
  title: "",
  description: "",
  dueDate: "",
};

const blankEventForm = {
  title: "",
  description: "",
  eventDate: todayString(),
};

export default function Analytics() {
  const navigate = useNavigate();
  const [profile, setProfile] = useState(null);
  const [tasks, setTasks] = useState([]);
  const [events, setEvents] = useState([]);
  const [loading, setLoading] = useState(true);
  const [taskSaving, setTaskSaving] = useState(false);
  const [taskUpdatingId, setTaskUpdatingId] = useState(null);
  const [eventSaving, setEventSaving] = useState(false);
  const [error, setError] = useState("");
  const [taskForm, setTaskForm] = useState(blankTaskForm);
  const [eventForm, setEventForm] = useState(blankEventForm);
  const [currentMonth, setCurrentMonth] = useState(() => {
    const now = new Date();
    return new Date(now.getFullYear(), now.getMonth(), 1);
  });

  useEffect(() => {
    async function loadDashboard() {
      try {
        const [profileData, taskData, eventData] = await Promise.all([
          fetchProfile(),
          fetchTasks(),
          fetchEvents(),
        ]);

        setProfile(profileData);
        setTasks(taskData);
        setEvents(eventData);
        setError("");
      } catch (err) {
        setError(err.message);
        if (err.message === "Your session has expired or you are not logged in.") {
          navigate("/login", { replace: true });
        }
      } finally {
        setLoading(false);
      }
    }

    loadDashboard();
  }, [navigate]);

  const stats = useMemo(() => {
    const completedCount = tasks.filter((task) => task.completed).length;
    const pendingCount = tasks.length - completedCount;
    const upcomingEvents = events.filter((event) => event.eventDate >= todayString()).length;

    return [
      {
        title: "Open Tasks",
        value: pendingCount,
        description: "Tasks still waiting to be completed.",
      },
      {
        title: "Completed Tasks",
        value: completedCount,
        description: "Finished items on your study plan.",
      },
      {
        title: "Upcoming Events",
        value: upcomingEvents,
        description: "Calendar items scheduled from today forward.",
      },
      {
        title: "Created By AI",
        value: tasks.filter((task) => task.createdBy === "AI").length + events.filter((event) => event.createdBy === "AI").length,
        description: "Planner items generated by AI.",
      },
    ];
  }, [events, tasks]);

  const completedTaskCount = useMemo(() => tasks.filter((task) => task.completed).length, [tasks]);

  const calendarDays = useMemo(() => buildCalendarDays(currentMonth, events), [currentMonth, events]);

  async function handleTaskSubmit(event) {
    event.preventDefault();
    setTaskSaving(true);
    setError("");

    try {
      const created = await createTask({
        title: taskForm.title,
        description: taskForm.description || null,
        dueDate: taskForm.dueDate || null,
        completed: false,
        createdBy: "USER",
      });
      setTasks((prev) => [...prev, created]);
      setTaskForm(blankTaskForm);
    } catch (err) {
      setError(err.message);
    } finally {
      setTaskSaving(false);
    }
  }

  async function handleEventSubmit(event) {
    event.preventDefault();
    setEventSaving(true);
    setError("");

    try {
      const created = await createEvent({
        title: eventForm.title,
        description: eventForm.description || null,
        eventDate: eventForm.eventDate,
        createdBy: "USER",
      });
      setEvents((prev) => [...prev, created].sort((a, b) => a.eventDate.localeCompare(b.eventDate)));
      setEventForm((prev) => ({ ...blankEventForm, eventDate: prev.eventDate }));
    } catch (err) {
      setError(err.message);
    } finally {
      setEventSaving(false);
    }
  }

  async function handleToggleTask(task) {
    setError("");
    const nextCompleted = !task.completed;
    setTaskUpdatingId(task.id);
    setTasks((prev) => prev.map((item) => (item.id === task.id ? { ...item, completed: nextCompleted } : item)));

    try {
      const updated = await updateTask(task.id, { completed: nextCompleted });
      setTasks((prev) =>
        prev.map((item) =>
          item.id === task.id
            ? {
                ...item,
                ...updated,
                completed: typeof updated.completed === "boolean" ? updated.completed : nextCompleted,
              }
            : item
        )
      );
    } catch (err) {
      setTasks((prev) => prev.map((item) => (item.id === task.id ? { ...item, completed: task.completed } : item)));
      setError(err.message);
    } finally {
      setTaskUpdatingId(null);
    }
  }

  async function handleDeleteTask(taskId) {
    setError("");
    try {
      await deleteTask(taskId);
      setTasks((prev) => prev.filter((task) => task.id !== taskId));
    } catch (err) {
      setError(err.message);
    }
  }

  async function handleDeleteEvent(eventId) {
    setError("");
    try {
      await deleteEvent(eventId);
      setEvents((prev) => prev.filter((item) => item.id !== eventId));
    } catch (err) {
      setError(err.message);
    }
  }

  function showPreviousMonth() {
    setCurrentMonth((prev) => new Date(prev.getFullYear(), prev.getMonth() - 1, 1));
  }

  function showNextMonth() {
    setCurrentMonth((prev) => new Date(prev.getFullYear(), prev.getMonth() + 1, 1));
  }

  return (
    <>
      <Helmet>
        <title>Productivity Hub</title>
      </Helmet>

      <main className="main main--quizzes">
        <section className="notesHeader">
          <div className="quizzesHeader__title">
            <div className="notesHeader__icon notesHeader__icon--image" aria-hidden="true">
              <img
                src={productivityHubLightImage}
                alt=""
                className="pageHeader__logo pageHeader__logo--productivity pageHeader__logo--light"
              />
              <img
                src={productivityHubDarkImage}
                alt=""
                className="pageHeader__logo pageHeader__logo--productivity pageHeader__logo--dark"
              />
            </div>
            <div>
              <h1>Productivity Hub</h1>
              <p>
                {profile?.name
                  ? `${profile.name}'s study dashboard with tasks and calendar planning.`
                  : "Your study dashboard with tasks and calendar planning."}
              </p>
            </div>
          </div>
        </section>

        {loading ? (
          <p>Loading productivity hub...</p>
        ) : (
          <>
            <section className="quizStats analyticsStats">
              {stats.map((stat) => (
                <article className="quizStatCard" key={stat.title}>
                  <h2>{stat.title}</h2>
                  <div className="quizStatCard__value">{stat.value}</div>
                  <p>{stat.description}</p>
                </article>
              ))}
            </section>

            <section className="analyticsDashboard">
              <article className="quizCard analyticsCard analyticsCard--calendar">
                <div className="quizCard__top">
                  <span className="quizCard__tag">Calendar</span>
                  <span className="quizCard__level quizCard__level--easy">{monthLabel(currentMonth)}</span>
                </div>

                <h2>Study Calendar</h2>
                <p className="quizCard__meta">Track assignments, reviews, and AI-generated study blocks.</p>

                <div className="analyticsCalendarToolbar">
                  <button type="button" className="quizActionBtn quizActionBtn--secondary" onClick={showPreviousMonth}>
                    Previous
                  </button>
                  <strong>{monthLabel(currentMonth)}</strong>
                  <button type="button" className="quizActionBtn quizActionBtn--secondary" onClick={showNextMonth}>
                    Next
                  </button>
                </div>

                <div className="analyticsCalendarHead">
                  {["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"].map((day) => (
                    <span key={day}>{day}</span>
                  ))}
                </div>

                <div className="analyticsCalendarGrid">
                  {calendarDays.map((day) => (
                    <article
                      key={day.dateKey}
                      className={`analyticsCalendarDay${day.isCurrentMonth ? "" : " analyticsCalendarDay--muted"}${day.isToday ? " analyticsCalendarDay--today" : ""}`}
                    >
                      <div className="analyticsCalendarDay__number">{day.dayNumber}</div>
                      <div className="analyticsCalendarDay__events">
                        {day.events.slice(0, 2).map((item) => (
                          <div className="analyticsCalendarPill" key={item.id}>
                            {item.title}
                          </div>
                        ))}
                        {day.events.length > 2 && (
                          <div className="analyticsCalendarMore">+{day.events.length - 2} more</div>
                        )}
                      </div>
                    </article>
                  ))}
                </div>

                <form className="analyticsForm" onSubmit={handleEventSubmit}>
                  <h3>Add Calendar Event</h3>
                  <div className="quizOptionGrid">
                    <label className="quizField">
                      <span>Title</span>
                      <input
                        value={eventForm.title}
                        onChange={(event) => setEventForm((prev) => ({ ...prev, title: event.target.value }))}
                        placeholder="Ex: Biology exam review"
                      />
                    </label>

                    <label className="quizField">
                      <span>Date</span>
                      <input
                        type="date"
                        value={eventForm.eventDate}
                        onChange={(event) => setEventForm((prev) => ({ ...prev, eventDate: event.target.value }))}
                      />
                    </label>
                  </div>

                  <label className="quizField">
                    <span>Description</span>
                    <textarea
                      value={eventForm.description}
                      onChange={(event) => setEventForm((prev) => ({ ...prev, description: event.target.value }))}
                      placeholder="What do you want to remember for this date?"
                    />
                  </label>

                  <button className="quizActionBtn quizActionBtn--primary" type="submit" disabled={eventSaving}>
                    {eventSaving ? "Saving..." : "Add Event"}
                  </button>
                </form>

                <div className="analyticsList">
                  <h3>Upcoming Events</h3>
                  {events.length === 0 ? (
                    <p className="analyticsEmpty">No calendar events yet.</p>
                  ) : (
                    events.map((item) => (
                      <article className="analyticsListItem" key={item.id}>
                        <div>
                          <strong>{item.title}</strong>
                          <p>{formatDate(item.eventDate)}</p>
                          {item.description && <p>{item.description}</p>}
                        </div>
                        <button
                          type="button"
                          className="quizActionBtn quizActionBtn--danger"
                          onClick={() => handleDeleteEvent(item.id)}
                        >
                          Delete
                        </button>
                      </article>
                    ))
                  )}
                </div>
              </article>

              <article className="quizCard analyticsCard">
                <div className="quizCard__top">
                  <span className="quizCard__tag">Tasks</span>
                  <span className="quizCard__level quizCard__level--medium">Planner</span>
                </div>

                <h2>Todo List</h2>
                <p className="quizCard__meta">Add work manually now, and later you can generate it with AI.</p>

                <form className="analyticsForm" onSubmit={handleTaskSubmit}>
                  <label className="quizField">
                    <span>Task Title</span>
                    <input
                      value={taskForm.title}
                      onChange={(event) => setTaskForm((prev) => ({ ...prev, title: event.target.value }))}
                      placeholder="Ex: Finish chapter 4 summary"
                    />
                  </label>

                  <label className="quizField">
                    <span>Description</span>
                    <textarea
                      value={taskForm.description}
                      onChange={(event) => setTaskForm((prev) => ({ ...prev, description: event.target.value }))}
                      placeholder="Optional details for this task"
                    />
                  </label>

                  <label className="quizField quizField--compact">
                    <span>Due Date</span>
                    <input
                      type="date"
                      value={taskForm.dueDate}
                      onChange={(event) => setTaskForm((prev) => ({ ...prev, dueDate: event.target.value }))}
                    />
                  </label>

                  <button className="quizActionBtn quizActionBtn--primary" type="submit" disabled={taskSaving}>
                    {taskSaving ? "Saving..." : "Add Task"}
                  </button>
                </form>

                <div className="analyticsList">
                  <h3>Your Tasks</h3>
                  <p className="analyticsTaskCount">
                    Completed {completedTaskCount} of {tasks.length} tasks
                  </p>
                  {tasks.length === 0 ? (
                    <p className="analyticsEmpty">No tasks yet.</p>
                  ) : (
                    tasks.map((task) => (
                      <article className={`analyticsListItem analyticsListItem--task${task.completed ? " analyticsListItem--done" : ""}`} key={task.id}>
                        <label className="analyticsTaskToggle">
                          <input
                            type="checkbox"
                            checked={task.completed}
                            disabled={taskUpdatingId === task.id}
                            onChange={() => handleToggleTask(task)}
                          />
                          <div>
                            <strong>{task.title}</strong>
                            <p>{task.dueDate ? `Due ${formatDate(task.dueDate)}` : "No due date"}</p>
                            {task.description && <p>{task.description}</p>}
                          </div>
                        </label>
                        <button
                          type="button"
                          className="quizActionBtn quizActionBtn--danger"
                          onClick={() => handleDeleteTask(task.id)}
                        >
                          Delete
                        </button>
                      </article>
                    ))
                  )}
                </div>
              </article>
            </section>

            {error && <p className="quizError">{error}</p>}
          </>
        )}
      </main>
    </>
  );
}
